export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}
export default function RootLayout({ children, params }) {
  return (
    <html lang="en">
      <body>
      <div>UserId header {params.userId}</div>
        {children}
      <div>UserId footer</div>
        </body>
    </html>
  )
}
