export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}
import './globals.css'
export default function RootLayout({ children , base }) {
    return (
        <html lang="en">
            <body>
                {children}
                {base}
            </body>
        </html>
    )
}
