import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  console.log('this is root laouyt');
  
  return (
    <html lang="en">
      <body>
        <header>
          <Link href='/'>Home</Link>
          <Link href='/server1'>Server 1</Link>
          <Link href='/server2'>Server 2</Link>
        </header>
        {children}
      </body>
    </html>
  )
}
