export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {



  return (
    <html lang="en">
      <body>
        <div>User headder </div>
        {children}
        <div>User footer</div>
      </body>
    </html>
  )
}
