export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default async function RootLayout({ children, params }) {

    const userId  = (await params).userId

    
    
    return (
        <>
            <div>UserId headder {userId}</div>
            {children}
            <div>UserId footer</div>
        </>

    )
}
